// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20211029230028_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Creature", b =>
                {
                    b.Property<int>("CreatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mythical")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Spieces")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CreatureId");

                    b.ToTable("Creatures");

                    b.HasData(
                        new
                        {
                            CreatureId = 1,
                            Age = 3,
                            Description = "He's a very good boy!",
                            Image = "https://images.unsplash.com/photo-1559743404-85fb2bd372d3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
                            Mythical = "No",
                            Name = "Gunnar",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 2,
                            Age = 1,
                            Description = "D'awe!",
                            Image = "https://images.unsplash.com/photo-1578584099737-351780c55f69?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80",
                            Mythical = "No",
                            Name = "Gus",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 3,
                            Age = 11,
                            Description = "Does not giggle. He's actually quite the jerk to be honest.",
                            Image = "https://images.unsplash.com/photo-1603349136288-95d87bd0a268?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=687&q=80",
                            Mythical = "No",
                            Name = "Mr. Gigglesworth",
                            Spieces = "Cat"
                        },
                        new
                        {
                            CreatureId = 4,
                            Age = 5,
                            Description = "What can we do? It's the only name he responds to.",
                            Image = "https://images.unsplash.com/photo-1552053831-71594a27632d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=662&q=80",
                            Mythical = "No",
                            Name = "Dog",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 5,
                            Age = 75,
                            Description = "This may actually be Tim Curry. We're not entirely sure.",
                            Image = "https://i.pinimg.com/564x/0a/40/7e/0a407e1fd8c113f0d29564f116f4c64a.jpg",
                            Mythical = "Yes",
                            Name = "Tim Curry",
                            Spieces = "Minotaur"
                        },
                        new
                        {
                            CreatureId = 6,
                            Age = 400,
                            Description = "Self-named. Good luck.",
                            Image = "https://images.unsplash.com/photo-1614770596508-de1d826c3765?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzB8fGRyYWdvbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
                            Mythical = "Yes",
                            Name = "Hotdog",
                            Spieces = "Dragon"
                        },
                        new
                        {
                            CreatureId = 7,
                            Age = 50,
                            Description = "High energy! Walks are a must!",
                            Image = "https://images.unsplash.com/photo-1521217155737-0d5632e9813f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=687&q=80",
                            Mythical = "No",
                            Name = "Snaps",
                            Spieces = "Turtle"
                        },
                        new
                        {
                            CreatureId = 8,
                            Age = 5,
                            Description = "Eats butterflies. Like, all the time.",
                            Image = "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=687&q=80",
                            Mythical = "No",
                            Name = "Jerry",
                            Spieces = "Cat"
                        },
                        new
                        {
                            CreatureId = 9,
                            Age = 5,
                            Description = "Great with kids!",
                            Image = "https://images.unsplash.com/photo-1554692936-82776f9406db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                            Mythical = "No",
                            Name = "Sir Barkington",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 10,
                            Age = 7,
                            Description = "Does not care for laser pointers.",
                            Image = "https://images.unsplash.com/photo-1561948955-570b270e7c36?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=601&q=80",
                            Mythical = "No",
                            Name = "Samantha",
                            Spieces = "Cat"
                        },
                        new
                        {
                            CreatureId = 11,
                            Age = 1,
                            Description = "Only has three legs, but eats like he has all four!",
                            Image = "https://images.unsplash.com/photo-1452721226468-f95fb66ebf83?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8aGFtc3RlcnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
                            Mythical = "No",
                            Name = "Wheels",
                            Spieces = "Hamster"
                        },
                        new
                        {
                            CreatureId = 12,
                            Age = 1,
                            Description = "Born on Xmas.",
                            Image = "https://images.unsplash.com/photo-1609260057679-1b9f08ea0dc5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=687&q=80",
                            Mythical = "No",
                            Name = "Mistletoe",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 13,
                            Age = 2,
                            Description = "He's a snuggler!",
                            Image = "https://images.unsplash.com/photo-1544568100-847a948585b9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1074&q=80",
                            Mythical = "No",
                            Name = "Flops",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 14,
                            Age = 8,
                            Description = "What makes him mythical? Wouldn't you like to know...",
                            Image = "https://images.unsplash.com/photo-1517178271410-0b2a6480952f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=957&q=80",
                            Mythical = "Yes",
                            Name = "Sphinx",
                            Spieces = "Cat"
                        },
                        new
                        {
                            CreatureId = 15,
                            Age = 297,
                            Description = "Mostly keeps to himself. Occasionally razes.",
                            Image = "https://images.unsplash.com/photo-1577493340887-b7bfff550145?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=640&q=80",
                            Mythical = "Yes",
                            Name = "Mortimer",
                            Spieces = "Dragon"
                        },
                        new
                        {
                            CreatureId = 16,
                            Age = 56,
                            Description = "Twins. This one is dumber than the other one.",
                            Image = "https://ameliamellorsfantasticnarratograph.files.wordpress.com/2018/02/harpy2.jpg",
                            Mythical = "Yes",
                            Name = "Dee",
                            Spieces = "Harpy"
                        },
                        new
                        {
                            CreatureId = 17,
                            Age = 56,
                            Description = "Twins. This one is smarter than the other one.",
                            Image = "https://ameliamellorsfantasticnarratograph.files.wordpress.com/2018/02/harpy2.jpg",
                            Mythical = "Yes",
                            Name = "Dum",
                            Spieces = "Harpy"
                        },
                        new
                        {
                            CreatureId = 18,
                            Age = 40,
                            Description = "Pretty territorial. Not really sure we should be selling this.",
                            Image = "https://static.wikia.nocookie.net/forgottenrealms/images/5/5b/Axe_beak-5e.jpg/revision/latest/scale-to-width-down/350?cb=20200917222507",
                            Mythical = "Yes",
                            Name = "Gwen",
                            Spieces = "Axe Beak"
                        },
                        new
                        {
                            CreatureId = 19,
                            Age = 19,
                            Description = "An old circus bear looking for a good home to retire in. Comes with his own ball!",
                            Image = "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmVhcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                            Mythical = "No",
                            Name = "Huggy",
                            Spieces = "Bear"
                        },
                        new
                        {
                            CreatureId = 20,
                            Age = 4,
                            Description = "Just another cat. Same as the other ones.",
                            Image = "https://images.unsplash.com/photo-1543852786-1cf6624b9987?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1974&q=80",
                            Mythical = "No",
                            Name = "Dimetrius",
                            Spieces = "Cat"
                        },
                        new
                        {
                            CreatureId = 21,
                            Age = 9,
                            Description = "Name is more of a description really.",
                            Image = "https://static.turbosquid.com/Preview/2014/12/10__15_52_12/Hellhound_1.jpg2737221e-11c1-450b-bc32-0e86ae7d144fZoom.jpg",
                            Mythical = "Yes",
                            Name = "Stench",
                            Spieces = "Hellhound"
                        },
                        new
                        {
                            CreatureId = 22,
                            Age = 3,
                            Description = "Well she's just the most adorable thing you ever saw!",
                            Image = "https://images.unsplash.com/photo-1611003228941-98852ba62227?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1074&q=80",
                            Mythical = "No",
                            Name = "Sprinkle",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 23,
                            Age = 2,
                            Description = "The absolute froofiest!",
                            Image = "https://images.unsplash.com/photo-1591946614720-90a587da4a36?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
                            Mythical = "No",
                            Name = "Mildred",
                            Spieces = "Dog"
                        },
                        new
                        {
                            CreatureId = 24,
                            Age = 1,
                            Description = "Look, we just don't like cats ok? Please take him.",
                            Image = "https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=715&q=80",
                            Mythical = "No",
                            Name = "Friskers",
                            Spieces = "Cat"
                        },
                        new
                        {
                            CreatureId = 25,
                            Age = 1,
                            Description = "Don't get too attached.",
                            Image = "https://images.unsplash.com/photo-1579161256825-57ba3094f057?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80",
                            Mythical = "No",
                            Name = "Floater",
                            Spieces = "Goldfish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
